export const MAX_DURATION = 120
export const MIN_DURATION = 1

export const MAX_POPULARITY = 1_000_000
export const MIN_POPULARITY = 0

export const MIN_RATING = 0.5
export const MAX_RATING = 5

export const MIN_PRICE = 150
export const MAX_PRICE = 10_000

export const MAX_DETAILS_LENGTH = 150
export const MIN_DETAILS_LENGTH = 30

// export const REGEX_IMG_TYPE = /image\/.*/

export const MAX_IMG_SIZE_MB = 20
export const MAX_IMG_SIZE_BYTES = MAX_IMG_SIZE_MB * 1024 ** 2
export const INVALID_IMAGE_FEEDBACK = `Choose an image file that is not larger than ${MAX_IMG_SIZE_MB}MB`
export const INVALID_URL_FEEDBACK = `The URL should begin with https://images.unsplash.com/photo.`
// export const validators = {
//     duration,
//     popularity,
//     city,
//     rating,
//     priceOriginal,
//     priceOffered,
//     details,
// }


export const COUNTRIES = 
{
"afghanistan"                      : "Afghanistan",
"albania"                          : "Albania",
"algeria"                          : "Algeria",
"andorra"                          : "Andorra",
"angola"                           : "Angola",
"antigua-and-barbuda"              : "Antigua and Barbuda",
"argentina"                        : "Argentina",
"armenia"                          : "Armenia",
"aruba"                            : "Aruba",
"australia"                        : "Australia",
"austria"                          : "Austria",
"azerbaijan"                       : "Azerbaijan",
"bahamas"                          : "The Bahamas",
"bahrain"                          : "Bahrain",
"bangladesh"                       : "Bangladesh",
"barbados"                         : "Barbados",
"belarus"                          : "Belarus",
"belgium"                          : "Belgium",
"belize"                           : "Belize",
"benin"                            : "Benin",
"bhutan"                           : "Bhutan",
"bolivia"                          : "Bolivia",
"bonaire"                          : "Bonaire",
"bosnia-and-herzegovina"           : "Bosnia and Herzegovina",
"botswana"                         : "Botswana",
"brazil"                           : "Brazil",
"brunei"                           : "Brunei",
"bulgaria"                         : "Bulgaria",
"burkina-faso"                     : "Burkina Faso",
"burundi"                          : "Burundi",
"cambodia"                         : "Cambodia",
"cameroon"                         : "Cameroon",
"canada"                           : "Canada",
"cape-verde"                       : "Cape Verde",
"central-african-republic"         : "The Central-African Republic",
"chad"                             : "Chad",
"chile"                            : "Chile",
"china"                            : "China",
"colombia"                         : "Colombia",
"comoros"                          : "Comoros",
"congo-democratic-republic-of-the" : "Democratic Republic of the Congo",
"congo-republic-of-the"            : "Republic of the Congo",
"costa-rica"                       : "Costa Rica",
"cote-d-ivoire"                    : "Côte d’ Ivoire",
"croatia"                          : "Croatia",
"cuba"                             : "Cuba",
"curacao"                          : "Curaçao",
"cyprus"                           : "Cyprus",
"czech-republic"                   : "The Czech Republic",
"denmark"                          : "Denmark",
"djibouti"                         : "Djibouti",
"dominica"                         : "Dominica",
"dominican-republic"               : "The Dominican Republic",
"east-timor"                       : "East Timor",
"ecuador"                          : "Ecuador",
"egypt"                            : "Egypt",
"el-salvador"                      : "El Salvador",
"england"                          : "England",
"equatorial-guinea"                : "Equatorial Guinea",
"eritrea"                          : "Eritrea",
"estonia"                          : "Estonia",
"ethiopia"                         : "Ethiopia",
"europe"                           : "Europe",
"fiji"                             : "Fiji",
"finland"                          : "Finland",
"france"                           : "France",
"gabon"                            : "Gabon",
"gambia"                           : "The Gambia",
"georgia"                          : "Georgia",
"germany"                          : "Germany",
"ghana"                            : "Ghana",
"greece"                           : "Greece",
"greenland"                        : "Greenland",
"grenada"                          : "Grenada",
"guadeloupe"                       : "Guadeloupe",
"guam"                             : "Guam",
"guatemala"                        : "Guatemala",
"guinea"                           : "Guinea",
"guinea-bissau"                    : "Guinea-Bissau",
"guyana"                           : "Guyana",
"haiti"                            : "Haiti",
"honduras"                         : "Honduras",
"hongkong"                         : "Hong Kong",
"hungary"                          : "Hungary",
"iceland"                          : "Iceland",
"india"                            : "India",
"indonesia"                        : "Indonesia",
"iran"                             : "Iran",
"iraq"                             : "Iraq",
"ireland"                          : "Ireland",
"israel"                           : "Israel",
"italy"                            : "Italy",
"jamaica"                          : "Jamaica",
"japan"                            : "Japan",
"jordan"                           : "Jordan",
"kazakhstan"                       : "Kazakhstan",
"kenya"                            : "Kenya",
"kiribati"                         : "Kiribati",
"north-korea"                      : "Korea, North",
"south-korea"                      : "Korea, South",
"kosovo"                           : "Kosovo",
"kuwait"                           : "Kuwait",
"kyrgyzstan"                       : "Kyrgyzstan",
"laos"                             : "Laos",
"latvia"                           : "Latvia",
"lebanon"                          : "Lebanon",
"lesotho"                          : "Lesotho",
"liberia"                          : "Liberia",
"libya"                            : "Libya",
"liechtenstein"                    : "Liechtenstein",
"lithuania"                        : "Lithuania",
"luxembourg"                       : "Luxembourg",
"macau"                            : "Macao",
"madagascar"                       : "Madagascar",
"malawi"                           : "Malawi",
"malaysia"                         : "Malaysia",
"maldives"                         : "The Maldives",
"mali"                             : "Mali",
"malta"                            : "Malta",
"marshall-islands"                 : "The Marshall Islands",
"mauritania"                       : "Mauritania",
"mauritius"                        : "Mauritius",
"mexico"                           : "Mexico",
"micronesia"                       : "Micronesia",
"moldova"                          : "Moldova",
"monaco"                           : "Monaco",
"mongolia"                         : "Mongolia",
"montenegro"                       : "Montenegro",
"morocco"                          : "Morocco",
"mozambique"                       : "Mozambique",
"myanmar"                          : "Myanmar",
"namibia"                          : "Namibia",
"nauru"                            : "Nauru",
"nepal"                            : "Nepal",
"netherlands"                      : "The Netherlands",
"new-caledonia"                    : "New Caledonia",
"new-zealand"                      : "New Zealand",
"nicaragua"                        : "Nicaragua",
"niger"                            : "Niger",
"nigeria"                          : "Nigeria",
"niue"                             : "Niue",
"north-macedonia"                  : "North Macedonia",
"northern-ireland"                 : "Northern Ireland",
"norway"                           : "Norway",
"oman"                             : "Oman",
"pakistan"                         : "Pakistan",
"palau"                            : "Palau",
"palestine"                        : "Palestine",
"panama"                           : "Panama",
"papua-new-guinea"                 : "Papua New Guinea",
"paraguay"                         : "Paraguay",
"peru"                             : "Peru",
"philippines"                      : "The Philippines",
"poland"                           : "Poland",
"portugal"                         : "Portugal",
"puerto-rico"                      : "Puerto Rico",
"qatar"                            : "Qatar",
"romania"                          : "Romania",
"russia"                           : "Russia",
"rwanda"                           : "Rwanda",
"saba"                             : "Saba",
"saint-kitts-and-nevis"            : "Saint Kitts and Nevis",
"saint-lucia"                      : "Saint Lucia",
"st-patrick"                       : "Saint Patrick",
"saint-vincent-and-the-grenadines" : "Saint Vincent and the Grenadines",
"samoa"                            : "Samoa",
"san-marino"                       : "San Marino",
"sao-tome-and-principe"            : "São Tomé and Príncipe",
"saudi-arabia"                     : "Saudi Arabia",
"scotland"                         : "Scotland",
"senegal"                          : "Senegal",
"serbia"                           : "Serbia",
"seychelles"                       : "The Seychelles",
"sierra-leone"                     : "Sierra Leone",
"singapore"                        : "Singapore",
"slovakia"                         : "Slovakia",
"slovenia"                         : "Slovenia",
"solomon-islands"                  : "Solomon The Islands",
"somalia"                          : "Somalia",
"south-africa"                     : "South Africa",
"south-sudan"                      : "South Sudan",
"spain"                            : "Spain",
"sri-lanka"                        : "Sri Lanka",
"st-eustatius"                     : "St. Eustatius",
"st-martin"                        : "St. Martin",
"sudan"                            : "Sudan",
"suriname"                         : "Suriname",
"swaziland"                        : "Swaziland",
"sweden"                           : "Sweden",
"switzerland"                      : "Switzerland",
"syria"                            : "Syria",
"taiwan"                           : "Taiwan",
"tajikistan"                       : "Tajikistan",
"tanzania"                         : "Tanzania",
"thailand"                         : "Thailand",
"arab-league"                      : "the Arab League",
"faroe-islands"                    : "the Faroe Islands",
"northern-mariana-islands"         : "the Northern Mariana Islands",
"togo"                             : "Togo",
"tonga"                            : "Tonga",
"trinidad-and-tobago"              : "Trinidad and Tobago",
"tunisia"                          : "Tunisia",
"turkey"                           : "Turkey",
"turkmenistan"                     : "Turkmenistan",
"tuvalu"                           : "Tuvalu",
"uganda"                           : "Uganda",
"ukraine"                          : "Ukraine",
"united-arab-emirates"             : "United Arab The Emirates",
"united-kingdom"                   : "The United Kingdom",
"united-states-of-america"         : "The United States",
"uruguay"                          : "Uruguay",
"uzbekistan"                       : "Uzbekistan",
"vanuatu"                          : "Vanuatu",
"vatican-city"                     : "Vatican City",
"venezuela"                        : "Venezuela",
"vietnam"                          : "Vietnam",
"wales"                            : "Wales",
"yemen"                            : "Yemen",
"zambia"                           : "Zambia",
"zimbabwe"                         : "Zimbabwe"
}   